# Matrixlarni hosil qilish va uning elementlarini chiqarish 

## Matrix1

In [7]:
import numpy as np
a = np.random.randint(1,10, size=(3,3))
print("Original matrix:")
print(a)
l = len(a)

for i in range(l):
    for j in range(l):
        a[i,j] = 10 * i

a

Original matrix:
[[3 6 6]
 [6 4 3]
 [8 7 4]]


array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20]])

In [8]:
import numpy as np
a = np.random.randint(1,10, size=(3,3))
print("Original matrix:")
print(a)
l = len(a)

for i in range(l):
    for j in range(l):
        a[j,i] = 5*j

a

Original matrix:
[[9 2 8]
 [3 3 2]
 [7 2 8]]


array([[ 0,  0,  0],
       [ 5,  5,  5],
       [10, 10, 10]])

In [13]:
import numpy as np
a = np.random.randint(1,10, size=(3,3))
print("Original matrix:")
print(a)
l = len(a)
k = 2
yigindi = 0
kopaytma = 1
print(f"Matritsa {k} - satr elementlari: ")
for i in range(k,k+1):
    for j in range(l):
        yigindi += a[i,j]
        kopaytma *= a[i,j]
        print(a[i,j])
   
print(f"Yi'gindi: {yigindi}\nKo'paytma: {kopaytma} ")



Original matrix:
[[7 3 9]
 [6 7 9]
 [7 3 6]]
Matritsa 2 - satr elementlari: 
7
3
6
Yi'gindi: 16
Ko'paytma: 126 


## array18

In [14]:
# matritsa ustun elementlari yig'indisi va ko'paytmasi 
import numpy as np
a = np.random.randint(1,10, size=(3,3))
print("Original matrix:")
print(a)
l = len(a)
k = 2
yigindi = 0
kopaytma = 1
print(f"Matritsa {k} - ustun elementlari: ")
for i in range(k,k+1):
    for j in range(l):
        yigindi += a[j,i]
        kopaytma *= a[j,i]
        print(a[j,i])
   
print(f"Yi'gindi: {yigindi}\nKo'paytma: {kopaytma} ")

Original matrix:
[[7 6 4]
 [8 4 2]
 [1 5 7]]
Matritsa 2 - ustun elementlari: 
4
2
7
Yi'gindi: 13
Ko'paytma: 56 


In [15]:
# matritsa ustun elementlari yig'indisi va ko'paytmasi 
# 2-usul
import numpy as np
a = np.random.randint(1,10, size=(3,3))
print("Original matrix:")
print(a)
l = len(a)
k = 2
yigindi = 0
kopaytma = 1
print(f"Matritsa {k} - ustun elementlari: ")
for i in range(l):
    for j in range(l):
        if i == k:
            yigindi += a[j,i]
            kopaytma *= a[j,i]
            print(a[j,i])
    
print(f"Yi'gindi: {yigindi}\nKo'paytma: {kopaytma} ")

Original matrix:
[[5 5 2]
 [6 1 6]
 [1 4 9]]
Matritsa 2 - ustun elementlari: 
2
6
9
Yi'gindi: 17
Ko'paytma: 108 


## array19

In [21]:
# matritsaning har bir satr elementlari yig'indisi
import numpy as np
a = np.random.randint(1,10, size=(3,3))
print("Original matrix:")
print(a)
l = len(a)

print(f"Matritsa {k} - satr elementlari: ")
for i in range(l):
    yigindi = 0
    for j in range(l):
        yigindi += a[i,j]
    print(f" {i} - satr yigindisi = {yigindi}")

   


Original matrix:
[[6 2 6]
 [6 4 4]
 [2 2 3]]
Matritsa 2 - satr elementlari: 
 0 - satr yigindisi = 14
 1 - satr yigindisi = 14
 2 - satr yigindisi = 7


## array20

In [36]:
# matritsaning har bir ustuni elementlari ko'paytmasi
import numpy as np
a = np.random.randint(1,10, size=(3,3))
print("Original matrix:")
print(a)
l = len(a)

for i in range(l):
    kopaytma = 1
    for j in range(l):
        kopaytma *= a[j,i]
    print(f" {i} - ustun yigindisi = {kopaytma}")

Original matrix:
[[1 5 9]
 [4 4 7]
 [2 1 3]]
 0 - ustun yigindisi = 8
 1 - ustun yigindisi = 20
 2 - ustun yigindisi = 189


## array21

In [37]:
# matritsaning har bir satri uchun toq indexli ustulari o'rta arifmetigini chiqarish (do not use if statement)
import numpy as np
a = np.random.randint(1,10, size=(5,5))
print("Original matrix:")
print(a)
l = len(a)

for i in range(l):
    yigindi = 0
    count = 0
    for j in range(1, l, 2):
        yigindi += a[i,j]
        count += 1
    result = yigindi / count
    print(f" {i} - satr o'rta arifmetigi = {result}")

Original matrix:
[[4 4 7 3 5]
 [1 5 6 4 4]
 [4 2 3 5 4]
 [5 5 5 4 9]
 [9 1 5 9 3]]
 0 - satr o'rta arifmetigi = 3.5
 1 - satr o'rta arifmetigi = 4.5
 2 - satr o'rta arifmetigi = 3.5
 3 - satr o'rta arifmetigi = 4.5
 4 - satr o'rta arifmetigi = 5.0


## array22

In [39]:
# matritsaning har bir ustuni uchun 2 ga karrali satrlarning yig'indisini chiqarish (do not use if statement)
import numpy as np
a = np.random.randint(1,10, size=(5,5))
print("Original matrix:")
print(a)
l = len(a)

for i in range(l):
    yigindi = 0
    for j in range(l):
        if a[j,i] % 2 == 0:
            yigindi += a[j,i]

    print(f" {i} - ustuning 2 ga karrali satrlarning yig'indisini  = {yigindi}")

Original matrix:
[[1 9 4 5 8]
 [7 8 4 6 1]
 [8 7 6 5 1]
 [2 6 5 9 6]
 [6 8 2 7 2]]
 0 - ustuning 2 ga karrali satrlarning yig'indisini  = 16
 1 - ustuning 2 ga karrali satrlarning yig'indisini  = 22
 2 - ustuning 2 ga karrali satrlarning yig'indisini  = 16
 3 - ustuning 2 ga karrali satrlarning yig'indisini  = 6
 4 - ustuning 2 ga karrali satrlarning yig'indisini  = 16


## array23


In [40]:
# matritsa har bir satrining eng kichik elementini chiqarish.
import numpy as np
a = np.random.randint(1,10, size=(5,5))
print("Original matrix:")
print(a)
l = len(a)

for i in range(l):
    min = a[i,0]
    for j in range(l):
        if a[i,j] < min:
            min = a[i,j]
    print(f" {i} - satrining eng kichik elementini   = {min}")

Original matrix:
[[2 1 7 8 4]
 [9 4 1 3 8]
 [6 4 2 1 6]
 [4 2 9 3 1]
 [4 4 5 3 8]]
 0 - satrining eng kichik elementini   = 1
 1 - satrining eng kichik elementini   = 1
 2 - satrining eng kichik elementini   = 1
 3 - satrining eng kichik elementini   = 1
 4 - satrining eng kichik elementini   = 3


## array24

In [45]:
# matritsa har bir ustunining  eng katta elementini chiqarish.
import numpy as np
a = np.random.randint(1,10, size=(5,5))
print("Original matrix:")
print(a)
l = len(a)

for i in range(l):
    max = a[0,i]
    for j in range(l):
        if a[j,i] > max:
            max = a[j,i]
    print(f" {i} - ustunning eng katta elementi   = {max}")

Original matrix:
[[7 6 6 3 5]
 [4 3 7 3 7]
 [7 2 7 6 9]
 [3 6 4 5 3]
 [5 9 3 3 7]]
 0 - ustunning eng katta elementi   = 7
 1 - ustunning eng katta elementi   = 9
 2 - ustunning eng katta elementi   = 7
 3 - ustunning eng katta elementi   = 6
 4 - ustunning eng katta elementi   = 9


## array25

In [61]:
# matritsa elementlari yig'indisi eng katta bo'lgan satrning indexsi va shu satr elementlari yig'indisini chiqarish.
import numpy as np
a = np.random.randint(1,10, size=(5,5))
print("Original matrix:")
print(a)
l = len(a)
maxi = 0
for i in range(l):
    sum = 0
    for j in range(l):
        sum += a[i,j]

    if sum > maxi:
        maxi = sum 
        indx = i
     
    print(f" {i} - satr yi'gindisi   = {sum}")
print(f"Elementlari yig'indisi eng katta bo'lgan satr indeksi = {indx} \nSatr elementlari yig'indisi = {maxi}")

Original matrix:
[[1 7 1 9 9]
 [1 3 4 8 1]
 [2 6 6 8 7]
 [6 7 5 7 6]
 [7 4 5 3 7]]
 0 - satr yi'gindisi   = 27
 1 - satr yi'gindisi   = 17
 2 - satr yi'gindisi   = 29
 3 - satr yi'gindisi   = 31
 4 - satr yi'gindisi   = 26
Elementlari yig'indisi eng katta bo'lgan satr indeksi = 3 
Satr elementlari yig'indisi = 31


## array26

In [76]:
# matritsa elementlari ko'paytmasi eng kichik bo'lgan ustunnig indexsi va shu  ustun elementlari ko'paytmasini chiqarish.
import numpy as np
a = np.random.randint(1,10, size=(3,3))
print("Original matrix:")
print(a)
l = len(a)

maxi = 999999999999
for i in range(l):
    sum = 1
    for j in range(l):
        sum *= a[j,i]

    if sum < maxi:
        maxi = sum 
        indx = i
     
    print(f" {i} - ustun elementlari ko'paytmasi   = {sum}")
print(f"Elementlari ko'paytmasi eng kichik bo'lgan ustun indexsi = {indx} \nElementlari ko'paytmasi = {maxi}")

Original matrix:
[[1 7 1]
 [4 7 5]
 [5 1 9]]
 0 - ustun elementlari ko'paytmasi   = 20
 1 - ustun elementlari ko'paytmasi   = 49
 2 - ustun elementlari ko'paytmasi   = 45
Elementlari ko'paytmasi eng kichik bo'lgan ustun indexsi = 0 
Elementlari ko'paytmasi = 20


## array27

In [89]:
# matritsa elementlari yig'indisi eng kichik bo'lgan satrning eng katta elementini chiqarish.
import numpy as np
a = np.random.randint(1,10, size=(5,5))
print("Original matrix:")
print(a)
l = len(a)
MIN = 999999999
MAX = 0

# 1- elementlari yig'indisi eng kichik bo'lgan satrni topib olamiz
for i in range(l):
    sum = 0
    for j in range(l):
        sum += a[i,j]

    if sum < MIN:
        MIN = sum 
        indx = i
    print(f" {i} - satr yi'gindisi   = {sum}")

# keyin ushbu satrdagi eng katta elementni topib natijani ekranga chiqaramiz
for row in range(l):
    for col in range(l):
        if row == indx:

            if a[row,col] > MAX:
                MAX = a[row,col]
     
    
print(f"Elementlari yig'indisi eng kichik bo'lgan satr indeksi = {indx} \nsatrning eng katta elementi = {MAX}")

Original matrix:
[[6 8 4 3 5]
 [3 7 8 6 4]
 [3 5 2 4 5]
 [4 1 2 7 1]
 [6 5 7 6 7]]
 0 - satr yi'gindisi   = 26
 1 - satr yi'gindisi   = 28
 2 - satr yi'gindisi   = 19
 3 - satr yi'gindisi   = 15
 4 - satr yi'gindisi   = 31
Elementlari yig'indisi eng kichik bo'lgan satr indeksi = 3 
satrning eng katta elementi = 7


## array28

In [94]:
# matritsa elementlari yig'indisi eng katta bo'lgan ustunning eng kichik elementini chiqarish.
import numpy as np
a = np.random.randint(1,10, size=(5,5))
print("Original matrix:")
print(a)
l = len(a)
MIN = 999999999
MAX = 0

# 1- elementlari yig'indisi eng katta bo'lgan ustunni topib olamiz
for i in range(l):
    sum = 0
    for j in range(l):
        sum += a[j,i]

    if sum > MAX:
        MAX = sum 
        indx = i
    print(f" {i} - ustun yi'gindisi   = {sum}")

# keyin ushbu ustundagi eng kichik elementni topib natijani ekranga chiqaramiz
for row in range(l):
    for col in range(l):
        if row == indx:

            if a[col,row] < MIN:
                MIN = a[col,row]
    
print(f"Elementlari yig'indisi eng katta bo'lgan ustun indeksi = {indx} \nustunning eng kichik elementi = {MIN}")

Original matrix:
[[2 9 3 5 7]
 [5 3 1 1 2]
 [7 7 8 9 8]
 [3 9 7 8 5]
 [3 7 7 8 5]]
 0 - ustun yi'gindisi   = 20
 1 - ustun yi'gindisi   = 35
 2 - ustun yi'gindisi   = 26
 3 - ustun yi'gindisi   = 31
 4 - ustun yi'gindisi   = 27
Elementlari yig'indisi eng katta bo'lgan ustun indeksi = 1 
ustunning eng kichik elementi = 3


## array29

In [106]:
# Har bir satrda, shu satr o'rta arifmetigidan kichik bo'lgan elementlar sonini chiqarish
import numpy as np
a = np.random.randint(1,10, size=(5,5), dtype=int)
print("Original matrix:")
print(a)
l = len(a)
MIN = 999999999
MAX = 0

# 1- har bir satr o'rta arifmetigi topib olamiz
for i in range(l):
    sum = 0
    for j in range(l):
        sum += a[i,j]

    arif = sum / l
    print(f"{i} - satr o'rta arifmetigi  = {arif}")
    
    # endi shu satr o'rta arifmetigidan kichik bo'lgan elementlar sonini topamiz va ekranga chiqaramiz
    count = 0
    for el in range(l):
        if a[i,el] < arif:
            count += 1
        
    print(f"{i} - satr o'rta arifmetigidan kichik bo'lgan elementlar soni = {count}")
            

    

Original matrix:
[[3 3 8 3 2]
 [5 6 1 5 5]
 [3 4 4 7 5]
 [9 2 3 1 1]
 [8 9 2 9 7]]
0 - satr o'rta arifmetigi  = 3.8
0 - satr o'rta arifmetigidan kichik bo'lgan elementlar soni = 4
1 - satr o'rta arifmetigi  = 4.4
1 - satr o'rta arifmetigidan kichik bo'lgan elementlar soni = 1
2 - satr o'rta arifmetigi  = 4.6
2 - satr o'rta arifmetigidan kichik bo'lgan elementlar soni = 3
3 - satr o'rta arifmetigi  = 3.2
3 - satr o'rta arifmetigidan kichik bo'lgan elementlar soni = 4
4 - satr o'rta arifmetigi  = 7.0
4 - satr o'rta arifmetigidan kichik bo'lgan elementlar soni = 1


## array30

In [112]:
# Har bir ustunda, shu ustun o'rta arifmetigidan katta bo'lgan elementlar sonini chiqarish
import numpy as np
a = np.random.randint(1,10, size=(5,5), dtype=int)
print("Original matrix:")
print(a)
l = len(a)
MIN = 999999999
MAX = 0

# 1- har bir ustun o'rta arifmetigi topib olamiz
for i in range(l):
    sum = 0
    for j in range(l):
        sum += a[j,i]

    arif = sum / l
    print(f"{i} - ustun o'rta arifmetigi  = {arif}")
    
    # endi shu ustun o'rta arifmetigidan katta bo'lgan elementlar sonini topamiz va ekranga chiqaramiz
    count = 0
    for el in range(l):
        if a[i,el] > arif:
            count += 1
        
    print(f"{i} - ustun o'rta arifmetigidan katta bo'lgan elementlar soni = {count}")
            

Original matrix:
[[1 7 5 3 5]
 [7 9 2 9 2]
 [3 6 9 7 9]
 [6 5 2 7 7]
 [7 7 3 7 4]]
0 - ustun o'rta arifmetigi  = 4.8
0 - ustun o'rta arifmetigidan katta bo'lgan elementlar soni = 3
1 - ustun o'rta arifmetigi  = 6.8
1 - ustun o'rta arifmetigidan katta bo'lgan elementlar soni = 3
2 - ustun o'rta arifmetigi  = 4.2
2 - ustun o'rta arifmetigidan katta bo'lgan elementlar soni = 4
3 - ustun o'rta arifmetigi  = 6.6
3 - ustun o'rta arifmetigidan katta bo'lgan elementlar soni = 2
4 - ustun o'rta arifmetigi  = 5.4
4 - ustun o'rta arifmetigidan katta bo'lgan elementlar soni = 3


## array31

In [6]:
# Matritsa barcha elementlari o'rta arifmetigiga, o'rta arifmetigi eng yaqin bo'lgan satr va ustun nomerini chiqarish
import numpy as np
a = np.random.randint(1,10, size=(5,5), dtype=int)
print("Original matrix:")
print(a)
l = len(a)
MIN = 999999999
MAX = 0
sum_all = 0
# 1- Matritsaning barcha elementlari o'rta arifmetigini topib olamiz

for i in range(l):
    for j in range(l):
        sum_all += a[i,j]

total_avg = sum_all / (l * l)

print(f"Matritsa barcha elementlari yi'gindisi  = {sum_all}")
print(f"Matritsa elementlari soni  = {l*l}")
print(f"Matritsa barcha elementlari o'rta arifmetigi  = {total_avg}")

# satr va ustun elementlari o'rta arifmetigini topib olamiz va barcha elementlari o'rta arifmetigiga eng yaqinini topib ekranga chiqaramiz
for row in range(1):
    row_sum = 0
    col_sum = 0
    for col in range(1):
        row_sum += a[row,col]
        col_sum += a[col,row]
    
    rows_avg = row_sum / l
    cols_avg = col_sum / l
    
    close_row = abs(rows_avg - total_avg)
    close_col = abs(cols_avg - total_avg)


for row in range(l):
    row_sum = 0
    col_sum = 0
    for col in range(l):
        row_sum += a[row,col]
        col_sum += a[col,row]
    
    rows_avg = row_sum / l
    cols_avg = col_sum / l
    
    print(f"{row} - satr o'rta arifmetigi  = {rows_avg}")
    print(f"{row} - ustun o'rta arifmetigi  = {cols_avg}")

    # barcha elementlari o'rta arifmetigiga eng yaqinini topish
    close_r = abs(rows_avg - total_avg)
    close_c = abs(cols_avg - total_avg)

    if close_r < close_row:
        row_indx = row
    
    if close_c < close_col:
        col_indx = row

    close_row = close_r
    close_col = close_c
    
print("\nBarcha elementlar o'rta arifmetigiga eng yaqin satr raqami", row_indx)
print("\nBarcha elementlar o'rta arifmetigiga eng yaqin ustun raqami", col_indx)   


Original matrix:
[[2 5 2 6 4]
 [1 1 5 5 5]
 [8 6 1 9 2]
 [1 4 3 2 3]
 [9 4 8 4 2]]
Matritsa barcha elementlari yi'gindisi  = 102
Matritsa elementlari soni  = 25
Matritsa barcha elementlari o'rta arifmetigi  = 4.08
0 - satr o'rta arifmetigi  = 3.8
0 - ustun o'rta arifmetigi  = 4.2
1 - satr o'rta arifmetigi  = 3.4
1 - ustun o'rta arifmetigi  = 4.0
2 - satr o'rta arifmetigi  = 5.2
2 - ustun o'rta arifmetigi  = 3.8
3 - satr o'rta arifmetigi  = 2.6
3 - ustun o'rta arifmetigi  = 5.2
4 - satr o'rta arifmetigi  = 5.4
4 - ustun o'rta arifmetigi  = 3.2

Barcha elementlar o'rta arifmetigiga eng yaqin satr raqami 4

Barcha elementlar o'rta arifmetigiga eng yaqin ustun raqami 4


In [7]:
from IPython.display import IFrame
IFrame(src="https://www.youtube.com/watch?v=XF8pCXZcdOI", width="560", height="315")

In [8]:
from IPython.display import IFrame 
IFrame(src="https://www.youtube.com/embed/fTaLQKNuOXU", width="560", height="315")