# Matrix Addition using Nested Loop

In [95]:
a = [[1,2,3],
     [4,5,6]]
     
b = [[5,7,4],
     [6,7,2]]

result = []
# iterate through rows
for i in range(len(a)):
    inner_list = []
    # iterate through columns
    for j in range(len(a[i])):
        # append sum of the elements of a and b matrix
        inner_list.append(a[i][j] + b[i][j])
    result.append(inner_list)

for i in result:
    print(i)

[6, 9, 7]
[10, 12, 8]


In [96]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


##  Matrix Addition using Nested List Comprehension

In [98]:
# Program to add two matrices using list comprehension
a = [[1,2,3], [4,5,6], [7,8,9]]
b = [[5,7,4], [6,7,2], [9,1,8]]

result = [[a[i][j]+b[i][j] for j in range(len(a[0]))] for i in range(len(a))]

for i in result:
    print(i)

[6, 9, 7]
[10, 12, 8]
[16, 9, 17]


## Matrix Transpose using Nested Loop

In [ ]:
# Program to transpose a matrix using a nested loop

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)

In [ ]:
''' Program to transpose a matrix using list comprehension'''

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]

for r in result:
   print(r

# Matrix Multiplication using Nested Loop

In [118]:
a = [[1,2,3], [4,5,6]]
b = [[5,7], [6,7]]

result = []
## creating output array with the integer of 0 
for i in range(len(a)):
    inner_list = []
    for j in range(len(b[i])):
        inner_list.append(0)
    result.append(inner_list)

print(result)

# iterate through rows of a 
for a_rows in range(len(a)):
    # iterate through columns of b
    for b_col in range(len(b[0])):
        # Iterate through rows of b
        for b_rows in range(len(b)):
            result[a_rows][b_col] += a[a_rows][b_rows] * b[b_rows][b_col]

print("a: ", a)
print("b: ", b)

print("result: ")
for i in result:
    print(i)

[[0, 0], [0, 0]]
a:  [[1, 2, 3], [4, 5, 6]]
b:  [[5, 7], [6, 7]]
result: 
[17, 21]
[50, 63]


In [ ]:
a = [[1,2,3], [4,5,6], [7,8,9]]
b = [[5,7], [6,7], [9,1]]

result = []
for i in range(len(a)):
    inner_list = []
    for j in range(len(b[i])):
        inner_list.append(0)
    result.append(inner_list)
print(result)

for i in range(len[b])


# Ikki o'lchamli massivelar. Matritsalar

## Matrix1

In [177]:
# A
a = np.zeros((5,5),dtype=int)
print("Initial array:\n", a)

for i in range(len(a)):
    for j in range(len(a[i])):
        if i == j:
            a[i][j] = 1

print("Result:")
for i in a:
    print(i)

Initial array:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result:
[1 0 0 0 0]
[0 1 0 0 0]
[0 0 1 0 0]
[0 0 0 1 0]
[0 0 0 0 1]


In [186]:
# B
a = np.zeros((5,5),dtype=int)
print("Initial array:\n", a)

count = 0
for i in range(len(a)):
    count +=1
    for j in range(len(a[i])):
        if j == len(a[i]) - count:
            a[i][j] = count

print("Result:")
for i in a:
    print(i)

Initial array:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result:
[0 0 0 0 1]
[0 0 0 2 0]
[0 0 3 0 0]
[0 4 0 0 0]
[5 0 0 0 0]


In [185]:
# C
a = np.zeros((5,5),dtype=int)
print("Initial array:\n", a)

count = 0
for i in range(len(a)-1, 0, -1):
    count +=1
    for j in range(len(a[i])):
        if i == j:
            a[i][j] = count

print("Result:")
for i in a:
    print(i)

Initial array:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result:
[0 0 0 0 0]
[0 4 0 0 0]
[0 0 3 0 0]
[0 0 0 2 0]
[0 0 0 0 1]


In [189]:
# D
a = np.zeros((5,5),dtype=int)
print("Initial array:\n", a)

for i in range(len(a)):
    for j in range(len(a[i])):
        if i == j:
            a[i][j] = (i + 1) * (i+2)

print("Result:")
for i in a:
    print(i)

Initial array:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result:
[2 0 0 0 0]
[0 6 0 0 0]
[ 0  0 12  0  0]
[ 0  0  0 20  0]
[ 0  0  0  0 30]


In [209]:
# E
a = np.zeros((5,5),dtype=int)
print("Initial array:\n", a)

L = len(a) 
count = 0
for i in range(len(a)):
    #for j in range(len(a[i])):
    if i == count:
        a[i][count] = 2
        
        if i + 1 < L:
            a[i][count+1] = 1
            a[i+1][count] = 1
    count += 1
            
print("Result:\n", a)


Initial array:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result:
 [[2 1 0 0 0]
 [1 2 1 0 0]
 [0 1 2 1 0]
 [0 0 1 2 1]
 [0 0 0 1 2]]


In [277]:
# F
a = np.zeros((5,5),dtype=int)
print("Initial array:\n", a)

count = len(a[0]) 
for i in range(len(a)):
    for j in range(count):
        a[i][j] = i+1
    
    count -=1

print("Result:")
for i in a:
    print(i)

Initial array:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Result:
[1 1 1 1 1]
[2 2 2 2 0]
[3 3 3 0 0]
[4 4 0 0 0]
[5 0 0 0 0]


In [273]:
# G 
a = np.zeros((5,5))
l = len(a)
print(a)
x = 4
for row in range(l-1, 0, -1):
    n = 5
    for col in range(l):
        if row <= l:
            a[row][x-col] = n
            n -= 1
    x-=1

a


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0.],
       [4., 5., 1., 2., 3.],
       [3., 4., 5., 1., 2.],
       [2., 3., 4., 5., 1.],
       [1., 2., 3., 4., 5.]])

In [278]:
# G 
a = np.zeros((5,5))
l = len(a)
print(a)
for row in range(l):
    for col in range(row+1):
        a[row, col] = l - (row - col)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5. 0. 0. 0. 0.]
 [4. 5. 0. 0. 0.]
 [3. 4. 5. 0. 0.]
 [2. 3. 4. 5. 0.]
 [1. 2. 3. 4. 5.]]


In [289]:
# H 
a = np.zeros((5,5))
l = len(a)
print(a)

for row in range(l):
    for col in range(l-row):
        a[row, col] = l - (l-(col+row+1))

a



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 0.],
       [3., 4., 5., 0., 0.],
       [4., 5., 0., 0., 0.],
       [5., 0., 0., 0., 0.]])

In [319]:
# I 
a = np.zeros((5,5))
l = len(a)
print(a)
for row in range(l):
    for col in range(l):
        if row == col:
            a[row,col] = row+1
            a[row, -(col+1)] = l - row
    
a

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 0., 0., 0., 5.],
       [0., 2., 0., 4., 0.],
       [0., 0., 3., 0., 0.],
       [0., 2., 0., 4., 0.],
       [1., 0., 0., 0., 5.]])

In [334]:
arr = np.random.randint(1,10, size=(5,5), dtype=int)
print(arr)
sum = 0
for i in range(len(arr)):
    for j in range(len(arr)):
        sum += arr[i][j]   
    print("The Sum of",i,"row ==", sum)
    sum = 0


[[6 4 2 5 8]
 [1 7 5 6 8]
 [1 5 5 9 4]
 [8 9 3 1 4]
 [5 9 6 5 4]]
The Sum of 0 row == 25
The Sum of 1 row == 27
The Sum of 2 row == 24
The Sum of 3 row == 25
The Sum of 4 row == 29


In [342]:
arr = np.random.randint(1,10, size=(5,5), dtype=int)
print(arr)
max = 0
for i in range(len(arr)):
    for j in range(len(arr)):
        if arr[i][j] > max:
            max = arr[i,j]   
    print("The Max of",i,"row ==", max)
    max = 0

[[2 8 9 7 7]
 [6 9 2 4 9]
 [2 1 3 9 1]
 [8 4 8 7 8]
 [1 6 9 1 9]]
The Max of 0 row == 9
The Max of 1 row == 9
The Max of 2 row == 9
The Max of 3 row == 8
The Max of 4 row == 9


In [346]:
arr = np.random.randint(1,10, size=(5,5), dtype=int)
print(arr)
max = 0
for i in range(len(arr)):
    for j in range(len(arr)):
        if arr[j][i] > max:
            max = arr[j,i]   
    print("The Max of",i,"column ==", max)
    max = 0

[[1 2 2 8 4]
 [5 5 4 5 6]
 [8 9 7 6 3]
 [7 8 7 7 6]
 [3 2 6 7 6]]
The Max of 0 column == 8
The Max of 1 column == 9
The Max of 2 column == 7
The Max of 3 column == 8
The Max of 4 column == 6


In [373]:
arr = np.random.randint(1,10, size=(5,5), dtype=int)
print(arr)
min = 99999
for i in range(len(arr)):
    for j in range(len(arr)):
        
        if arr[i][j] < min:
            min = arr[i][j]
            m,n = i,j   
    print("The Min of",i,"row ==", min)

print("The min value index of the the matrix = arr[",m,"][",n,"]" )

[[7 3 1 3 4]
 [8 2 6 8 3]
 [3 3 4 7 2]
 [7 6 6 7 2]
 [3 4 3 7 5]]
The Min of 0 row == 1
The Min of 1 row == 1
The Min of 2 row == 1
The Min of 3 row == 1
The Min of 4 row == 1
The min value index of the the matrix = arr[ 0 ][ 2 ]


In [389]:
# elementi eng kichik bo'lgan ustunni olib tashlash
arr = np.random.randint(1,10, size=(5,5), dtype=int)
print(arr)
min = 99999
for i in range(len(arr)):
    for j in range(len(arr)):
        
        if arr[j][i] < min:
            min = arr[j][i]
            m,n = j,i   
    print("The Min of",i,"column ==", min)

print("The min value index of the the matrix = arr[",n,"][",m,"]" )

arr_del = np.delete(arr,n,1)
arr_del

[[4 7 3 2 5]
 [3 5 8 4 4]
 [6 8 3 6 9]
 [1 3 3 5 9]
 [1 1 4 7 2]]
The Min of 0 column == 1
The Min of 1 column == 1
The Min of 2 column == 1
The Min of 3 column == 1
The Min of 4 column == 1
The min value index of the the matrix = arr[ 0 ][ 3 ]


array([[7, 3, 2, 5],
       [5, 8, 4, 4],
       [8, 3, 6, 9],
       [3, 3, 5, 9],
       [1, 4, 7, 2]])

In [387]:
arr_del = np.delete(arr,1,1)
arr

array([[5, 4, 4, 5, 6],
       [1, 5, 6, 4, 7],
       [2, 1, 9, 7, 9],
       [1, 5, 5, 9, 4],
       [4, 8, 2, 3, 4]])

In [388]:
arr_del

array([[5, 4, 5, 6],
       [1, 6, 4, 7],
       [2, 9, 7, 9],
       [1, 5, 9, 4],
       [4, 2, 3, 4]])

In [391]:
# elementi eng kichik bo'lgan satrni olib tashlash
arr = np.random.randint(1,10, size=(5,5), dtype=int)
print(arr)
min = 99999
for i in range(len(arr)):
    for j in range(len(arr)):
        
        if arr[i][j] < min:
            min = arr[i][j]
            m,n = i,j   
    print("The Min of",i,"column ==", min)

print("The min value index of the the matrix = arr[",m,"][",n,"]" )

arr_del = np.delete(arr,m,0)
arr_del

[[7 1 9 9 9]
 [5 5 2 4 6]
 [4 1 7 2 6]
 [4 9 7 9 6]
 [1 4 9 2 9]]
The Min of 0 column == 1
The Min of 1 column == 1
The Min of 2 column == 1
The Min of 3 column == 1
The Min of 4 column == 1
The min value index of the the matrix = arr[ 0 ][ 1 ]


array([[5, 5, 2, 4, 6],
       [4, 1, 7, 2, 6],
       [4, 9, 7, 9, 6],
       [1, 4, 9, 2, 9]])

In [420]:
# Max elementi bor satrni, 0-satr bilan almashtirish 
arr = np.random.randint(1,10, size=(5,5), dtype=int)
print(arr)
max = 0

for i in range(len(arr)):
    for j in range(len(arr)):
        
        if arr[i][j] > max:
            max = arr[i][j]
            row_indx,col_indx = i,j   
    print("The Min of",i,"column ==", max)

print("The min value index of the the matrix = arr[",row_indx,"][",col_indx,"]" )

arr[[0, row_indx]] = arr[[row_indx,0]]
arr

[[6 8 2 2 5]
 [8 1 2 3 1]
 [9 6 8 7 6]
 [7 2 8 3 7]
 [7 8 4 6 2]]
The Min of 0 column == 8
The Min of 1 column == 8
The Min of 2 column == 9
The Min of 3 column == 9
The Min of 4 column == 9
The min value index of the the matrix = arr[ 2 ][ 0 ]


array([[9, 6, 8, 7, 6],
       [8, 1, 2, 3, 1],
       [6, 8, 2, 2, 5],
       [7, 2, 8, 3, 7],
       [7, 8, 4, 6, 2]])

In [475]:
# Max elementi bor ustunni, 0-ustun bilan almashtirish 
arr = np.random.randint(1,10, size=(5,5), dtype=int)
print(arr)
max = 0

for i in range(len(arr)):
    for j in range(len(arr)):
        
        if arr[j][i] > max:
            max = arr[j][i]
            row_indx,col_indx = j,i   
    print("The max of",i,"column ==", max)

print("The max value index of the the matrix = arr[",col_indx,"][",row_indx,"]" )

arr[:,[0,col_indx]] = arr[:,[col_indx,0]]
arr


[[7 8 5 8 8]
 [1 9 7 2 7]
 [8 5 6 9 7]
 [3 3 9 3 3]
 [6 2 1 5 4]]
The max of 0 column == 8
The max of 1 column == 9
The max of 2 column == 9
The max of 3 column == 9
The max of 4 column == 9
The max value index of the the matrix = arr[ 1 ][ 1 ]


array([[8, 7, 5, 8, 8],
       [9, 1, 7, 2, 7],
       [5, 8, 6, 9, 7],
       [3, 3, 9, 3, 3],
       [2, 6, 1, 5, 4]])

In [484]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(arr)
for i in range(l):
    for j in range(i,l):
        a[i,j] = 1

print("Result:\n",a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
 [[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]


In [488]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(arr)
for i in range(l):
    for j in range(0,i+1):
        a[i,j] = 1

print("Result:")
print(a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [491]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(arr)
for i in range(l):
    for j in range(l-i-1, l):
        a[i,j] = 1

print("Result:")
print(a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [492]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(arr)
for i in range(l):
    for j in range(0, l-i):
        a[i,j] = 1

print("Result:")
print(a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [495]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(arr)
for i in range(l):
    for j in range(i, l-i):
        a[i,j] = 1

print("Result:")
print(a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [505]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(arr)
for i in range(l-1,0,-1):
    for j in range(l-1-i, i+1):
        a[i,j] = 1

print("Result:")
print(a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [512]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(arr)
for i in range(l):
    for j in range(i, l-i):
        a[i,j] = 1
    if i >= 2:
        for k in range(l-i-1, i):
            a[i,j] = 1

print("Result:")
print(a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [518]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(arr)
for i in range(l):
    if i <= 2:
        for j in range(i,l-i):
            a[i,j] = 1
    if i > 2:
        for k in range(l-1-i, i+1):
            a[i,k] = 1
            
print("Result:")
print(a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [520]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(arr)
for i in range(l):
    if i <= 2:
        for j in range(l-1-i,l):
            a[i,j] = 1
    if i > 2:
        for k in range(i, l):
            a[i,k] = 1
            
print("Result:")
print(a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]


In [523]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(arr)
for i in range(l):
    if i <= 2:
        for j in range(0,l-(l-i)+1):
            a[i,j] = 1
    if i >= 2:
        for k in range(0, l-i):
            a[i,k] = 1
            
print("Result:")
print(a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [8]:
a = np.zeros((5,5))
print("initial array:\n",a)
l = len(a)
for i in range(l):
    if i <= 2:
        for j in range(0,l-(l-i)+1):
            a[i,j] = 1
        for x in range(l-1-i, l):
            a[i,x] = 1
    if i >= 2:
        for k in range(0, l-i):
            a[i,k] = 1
        for y in range(i, l):
            a[i,y] = 1
            
print("Result:")
print(a)

initial array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Result:
[[1. 0. 0. 0. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 0. 0. 0. 1.]]


Original Array:
[[22 14  8 19  6]
 [ 1  1 21  5  7]
 [20 19  1  7 15]
 [11  2  1  5  1]
 [15 16 11 17 16]]
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


In [ ]:
import numpy as np 
a = np.random.randint(0,25, size=(5,5))
print("Original Array:")
print(a)
l = len(a)
min = 999
for i in range(l):
    for j in range(i,l):
        for k in range(j,l):
            for m in range(k,l):    
                if a[k,m] < min:
                    min  = a[k,m]
                    row_indx, col_indx = k,m


        print(min)



In [2]:
import numpy as np 
a = np.random.randint(1,10, size=(3,3))
print(a)
l = len(a)
for row in range(l):
    for col in range(l):
        Min = a[row,col]
        row_in, col_in = row,col
        for r in range(row,l):
            for c in range(col,l):
                if a[r,c] < Min:
                    Min = a[r,c]
                    row_in, col_in = r,c
        
        temp = a[row,col]
        a[row,col] = Min
        a[row_in,col_in] = temp
print("Result:")
print(a)

[[3 8 2]
 [8 8 4]
 [7 7 4]]
Result:
[[2 3 4]
 [4 7 8]
 [7 8 8]]
